version: '2'
services:
    server:
        image: linkeddatafragments/server.js
        ports:
        - "3000:3000"
        volumes:
        - ${DATA_DIR}:/data
        - ./config-server.json:/tmp/config.json
        command: /tmp/config.json 3000 ${LDF_WORKERS}
    client-web:
        image: linkeddatafragments/jquery-widget.js
        ports:
        - "8080:8080"
        volumes:
        - ./config-client.json:/tmp/settings.json
        - ./queries:/tmp/queries